name: release-extract-info
on:
  workflow_dispatch:
  release:
    type: [published]
jobs:
  statistics:
    name: extract-info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Run test statistics script
        id: extract
        run: |
          pip3 install -r .github/scripts/extract-kics-info/requirements.txt
          python3 .github/scripts/extract-kics-info/extract-info.py
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .github/scripts/extract-kics-info/extracted-info.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Clean generated files
        run : |
          rm -f \
          .github/scripts/extract-kics-info/categories.json \
          .github/scripts/extract-kics-info/cloudProviders.json \
          .github/scripts/extract-kics-info/platforms.json \
          .github/scripts/extract-kics-info/queries.json \
          .github/scripts/extract-kics-info/severities.json \
          .github/scripts/extract-kics-info/extracted-info.zip



