name: validate-queries-metadata

on:
  pull_request:
    paths:
    - "assets/queries/**/metadata.json"

jobs:
  validate-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - name: Run queries metadata validation script
        env:
          KICS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KICS_PR_NUMBER: ${{ github.event.number }}
        id: validator
        working-directory: .github/scripts/queries-validator/
        run: |
          pip3 install -r requirements.txt
          python3 queries-validator.py
