name: validate-ansible-samples

on:
  pull_request:
    paths:
    - "assets/queries/ansible/aws/**/test/*.yaml"
    - "assets/queries/ansible/azure/**/test/*.yaml"
    - "assets/queries/ansible/gcp/**/test/*.yaml"

jobs:
  lint-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1
        with:
          file_or_dir: assets/queries/ansible/
          config_file: .github/scripts/samples-linters/yamllint_ansible.yml
          strict: true
