name: validate-arm-samples

on:
  pull_request:
    paths:
      - "assets/queries/azureResourceManager/**/test/*.json"

jobs:
  lint-json-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Installing jsonlint
        run: |
          npm install -g jsonlint
      - name: Running JSON lint
        run: |
          python3 -u ".github/scripts/samples-linters/validate-syntax.py" \
            "assets/queries/azureResourceManager/**/test/*.json" \
            --linter jsonlint \
            --skip ".github/scripts/samples-linters/ignore-list/arm" -vv
